name: configurator_flutter
description: A new Flutter package project.
version: 1.0.4
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  intl: ^0.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  i18n_extension: ^11.0.11
  google_fonts: ^5.1.0

  parse_color: ^0.0.1
  collection: ^1.17.1
  yaml: ^3.1.2

  slang_flutter: ^3.0.0

  configurator:
    git:
      url: https://github.com/jmayobres/configurator.git
      ref: main
      path: configurator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
